import type { ShopGrievance } from "./grievance.ts";

/**
 * The 25 entries from docs/INDUSTRY_GRIEVANCES.md, converted into the typed
 * ShopGrievance schema per PRODUCT_SPEC.md §14. This is a data-modeling pass on
 * research already done, sourced, and reviewed - not new research (per
 * ARCHITECTURE_ASSESSMENT.md).
 *
 * Fidelity note, per §38's research ethic: structured fields (triggerConditions,
 * observations, progression) are only as detailed as the underlying source
 * actually supports. A single-anecdote grievance (e.g. #19 talent pipeline, #20
 * owner burnout - both explicitly flagged "under-sourced"/"cross-industry" in
 * the source doc) gets thin, honest structured fields rather than invented
 * elaborate progressions. Padding every entry to look equally rich would
 * misrepresent the evidence - the opposite of what §38 asks for.
 *
 * expression/targetPath/effect strings are deliberately human-readable prose,
 * not typed simulation-state paths yet - simulation-core's SimulationState
 * doesn't have equivalents for most of these yet (there is no cash-flow model,
 * no marketplace model, no maintenance-scheduling model). Tightening these to
 * real typed expressions is follow-up work once those systems exist, not a
 * blocker on cataloging the grievances themselves.
 *
 * None of these are wired into anything yet - no trigger engine, no simulation-
 * core consumer. This is the data; the engine that reads it is a separate,
 * later increment.
 */
export const CATALOGED_GRIEVANCES: ShopGrievance[] = [
  {
    id: "grievance.decimal-slip-scrap",
    title: "Decimal-slip scrap",
    category: "programming-control",
    severity: "scrap",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/worst-scrap-stories.254293/", accessedDate: "2026-08-13", summarizedClaim: "A machinist entered .177 instead of .117 off a poorly dimensioned drawing, scrapping roughly two days of labor and material on the mistake alone." },
    ],
    triggerConditions: [{ description: "Operator manually enters a dimension/offset from a drawing with ambiguous or crowded dimensioning.", expression: "manual value entry, no cross-check against a second source" }],
    latentStateEffects: [{ targetPath: "part geometry (future)", effect: "One or more features machined to the wrong dimension; irreversible once cut." }],
    observations: { visual: ["Finished feature visibly off from the print once measured."], process: ["No corroborating source (second read of the print, a callout, a peer check) was consulted before cutting."] },
    progression: [{ name: "entry", description: "Value keyed once, unchecked", observableSymptoms: [] }, { name: "irreversible", description: "Material removed to the wrong dimension", observableSymptoms: ["measured value does not match nominal"] }],
    consequences: [{ description: "Scrapped part; lost material and labor time.", severity: "scrap" }],
    appropriateResponses: [{ description: "Read the dimension from a second source (a callout, a table, a peer) before committing an entered value to a cut.", competencyIds: ["setup-verification", "tolerance-interpretation"] }],
    inappropriateResponses: [{ description: "Enter and cut immediately from a single read of a crowded drawing.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Cross-check any manually entered dimension against a second source before the first cut.", competencyIds: ["setup-verification"] }],
    competencies: ["setup-verification", "tolerance-interpretation"],
  },
  {
    id: "grievance.compounding-error-scrap-run",
    title: "Compounding-error scrap run",
    category: "quality-documentation",
    severity: "scrap",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/worst-scrap-stories.254293/", accessedDate: "2026-08-13", summarizedClaim: "Missing corner-break radii on ~$7,000/ea bushings; the attempted fix then cut too deep, scrapping 39 consecutive pieces before anyone stopped the run." },
    ],
    triggerConditions: [{ description: "A program error is 'corrected' without re-verifying the fix against the print before resuming a production run.", expression: "resume production after an unverified correction" }],
    latentStateEffects: [{ targetPath: "part geometry (future), batch state (future)", effect: "Every subsequent part in the run inherits the same (now wrong) correction until someone checks a part against the print." }],
    observations: { process: ["No first-article re-check was performed after the correction, before resuming full-rate production."] },
    progression: [
      { name: "initial-defect", description: "Corner-break radii missing from the program", observableSymptoms: ["first parts fail inspection"] },
      { name: "uncorroborated-fix", description: "A correction is applied without a first-article re-check", observableSymptoms: [] },
      { name: "compounding-scrap", description: "Production resumes at full rate on the unverified fix", observableSymptoms: ["every subsequent part shares the same defect"] },
    ],
    consequences: [{ description: "39 consecutive scrapped parts on a high-value item.", severity: "scrap" }],
    appropriateResponses: [{ description: "Run and fully inspect a first article after ANY program correction before resuming batch production.", competencyIds: ["quality-disposition", "setup-verification"] }],
    inappropriateResponses: [{ description: "Resume full-rate production immediately after a program fix, trusting the fix without re-verification.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Treat any post-correction resume as a new first-article event, not a continuation.", competencyIds: ["quality-disposition"] }],
    competencies: ["quality-disposition", "setup-verification"],
  },
  {
    id: "grievance.warpage-found-after-shipping",
    title: "Warpage found after shipping",
    category: "quality-documentation",
    severity: "scrap",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/worst-scrap-stories.254293/", accessedDate: "2026-08-13", summarizedClaim: "~20,000 lbs of machined plastic parts were returned for warping that was only detectable/measurable after delivery, not at final inspection." },
    ],
    triggerConditions: [{ description: "A material's dimensional stability changes after the shop's inspection window closes (e.g. stress relief continuing over days).", expression: "defect not present or not measurable at time of shipping inspection" }],
    latentStateEffects: [{ targetPath: "part geometry (future)", effect: "Continued dimensional change after release, outside the shop's control." }],
    observations: { dimensional: ["In-house inspection at time of shipment shows the part within tolerance."], process: ["Defect only becomes measurable well after the part leaves the building."] },
    progression: [{ name: "released-in-tolerance", description: "Part passes final inspection", observableSymptoms: [] }, { name: "post-shipment-drift", description: "Continued warpage over time/environment change", observableSymptoms: ["customer-side measurement fails"] }],
    consequences: [{ description: "Large-scale customer return well after the shop believed the job was closed.", severity: "scrap" }],
    appropriateResponses: [{ description: "Understand a material's known stress-relief/stability behavior and build dwell time into the process plan before final inspection for materials known to move.", competencyIds: ["process-monitoring", "quality-disposition"] }],
    inappropriateResponses: [{ description: "Treat final in-house inspection as the end of the risk window for a material known to continue moving.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Build a stabilization dwell into the process plan for materials with known post-machining movement.", competencyIds: ["process-monitoring"] }],
    competencies: ["process-monitoring", "quality-disposition"],
  },
  {
    id: "grievance.outside-process-ruins-finished-parts",
    title: "Outside process ruins finished parts",
    category: "quality-documentation",
    severity: "downtime",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/vendor-screw-ups-messed-up-parts.397251/", accessedDate: "2026-08-13", summarizedClaim: "A plating vendor destroyed 43 of 235 already-machined pieces; rework was deprioritized against new incoming work, and delivery slipped roughly two months." },
    ],
    triggerConditions: [{ description: "A finished part is sent to an outside process (plating, heat treat, coating) with no incoming inspection gate on return.", expression: "outside-process return accepted without re-inspection" }],
    latentStateEffects: [{ targetPath: "batch state (future)", effect: "A subset of an otherwise-complete batch becomes unusable after work the shop has no direct control over." }],
    observations: { visual: ["Visible plating/coating defects on return."], process: ["Rework work competes for capacity against new incoming orders and gets deprioritized."] },
    progression: [{ name: "sent-out", description: "Good parts shipped to an outside process", observableSymptoms: [] }, { name: "damaged-return", description: "Parts come back damaged", observableSymptoms: ["visible defect on incoming inspection"] }, { name: "deprioritized-rework", description: "Rework loses the capacity fight against new work", observableSymptoms: ["schedule slip"] }],
    consequences: [{ description: "~2 month delivery slip from a vendor-caused defect the shop did not create.", severity: "downtime" }],
    appropriateResponses: [{ description: "Treat outside-process returns as an incoming-inspection gate, and schedule rework capacity explicitly rather than letting it compete informally against new work.", competencyIds: ["quality-disposition", "process-monitoring"] }],
    inappropriateResponses: [{ description: "Accept outside-process returns straight into the shippable-inventory pile without re-inspection.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Always incoming-inspect parts returning from an outside process before counting them as shippable.", competencyIds: ["quality-disposition"] }],
    competencies: ["quality-disposition", "process-monitoring"],
  },
  {
    id: "grievance.hiding-scrap-under-schedule-pressure",
    title: "Hiding scrap under schedule pressure",
    category: "production-business-friction",
    severity: "safety-critical",
    validationStatus: "anecdotal",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/worst-scrap-stories.254293/", accessedDate: "2026-08-13", summarizedClaim: "Workers at one plant were found, during a shutdown, to have been dumping bad parts - and some good parts - into machine sumps rather than report scrap." },
    ],
    triggerConditions: [{ description: "Schedule/production pressure creates an incentive to hide a defect rather than report it.", expression: "scrap-reporting incentive misaligned with production-rate pressure" }],
    latentStateEffects: [{ targetPath: "quality records (future)", effect: "True scrap rate and defect root causes become invisible to management." }],
    observations: { process: ["Reported scrap rate looks better than actual process capability.", "Root cause data for real defects never reaches anyone who could fix the process."] },
    progression: [{ name: "pressure", description: "Production targets create an incentive to avoid reporting", observableSymptoms: [] }, { name: "concealment", description: "Bad (and sometimes good) parts are discarded outside the normal scrap-reporting channel", observableSymptoms: ["scrap disappears from records"] }],
    consequences: [{ description: "Root-cause blindness; the underlying process problem never gets fixed because it's never visible.", severity: "safety-critical" }],
    appropriateResponses: [{ description: "Report scrap through the real channel even under schedule pressure; a documented defect is fixable, a hidden one recurs invisibly.", competencyIds: ["safety-process-discipline", "quality-disposition"] }],
    inappropriateResponses: [{ description: "Dispose of a defective (or even a good) part outside the scrap-reporting process to avoid schedule scrutiny.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "A shop culture where reporting scrap is not punished disproportionately to the underlying mistake.", competencyIds: ["safety-process-discipline"] }],
    competencies: ["safety-process-discipline", "quality-disposition"],
  },
  {
    id: "grievance.overspeed-data-entry",
    title: "Overspeed data entry",
    category: "programming-control",
    severity: "machine-damage",
    validationStatus: "validated",
    sourceReferences: [
      { url: "https://oem.msu.edu/images/MiFACE/04MI180v1.pdf", accessedDate: "2026-08-13", summarizedClaim: "An operator entered 3000 RPM instead of 300 with a 110% feed override active; the spindle reached ~3300 RPM almost instantly, bending a soft-steel tool extension 90 degrees and throwing the shattered piece into the automatic tool changer." },
    ],
    triggerConditions: [{ description: "An entered spindle-speed value is off by an order of magnitude (e.g. a missing/extra digit) with no upper-bound sanity check, combined with an active feed/speed override.", expression: "enteredRpm far exceeds the tool/setup's safe operating range, no bound check" }],
    latentStateEffects: [{ targetPath: "cutting.spindleRpm, tool.edgeCondition, failure.activeMode", effect: "Near-instant catastrophic tool failure; ejected fragments can reach the tool changer." }],
    observations: { audio: ["Immediate, dramatic change in cutting sound consistent with instantaneous fracture, not gradual wear."], telemetry: ["Commanded RPM is inconsistent with the tool/operation's rated envelope."] },
    progression: [{ name: "entry", description: "Overspeed value entered and confirmed", observableSymptoms: [] }, { name: "near-instant-fracture", description: "Tool bends/fractures within moments of spindle-up", observableSymptoms: ["abrupt acoustic and load discontinuity"] }],
    consequences: [{ description: "Destroyed tooling, potential machine/tool-changer damage, real injury risk in the real-world incident this is drawn from.", severity: "machine-damage" }],
    appropriateResponses: [{ description: "Verify an entered spindle speed against the tool/operation's rated range before confirming, especially with an override active.", competencyIds: ["setup-verification", "safe-prove-out-reasoning"] }],
    inappropriateResponses: [{ description: "Confirm an entered value without a sanity check against the operation's expected range.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Treat any entered value that is an order of magnitude off from expectation as a stop-and-verify moment, not a typo to shrug off.", competencyIds: ["setup-verification"] }],
    competencies: ["setup-verification", "safe-prove-out-reasoning"],
  },
  {
    id: "grievance.setup-carried-over-from-prior-job",
    title: "Setup carried over from prior job",
    category: "setup",
    severity: "machine-damage",
    validationStatus: "validated",
    sourceReferences: [
      { url: "https://stacks.cdc.gov/view/cdc/167115", accessedDate: "2026-08-13", summarizedClaim: "Chuck jaw pressure was left at 170 psi from a prior job instead of the 300 psi required; the workpiece came loose at 1,500 RPM and the fixture was thrown across the shop." },
    ],
    triggerConditions: [{ description: "A machine setting from the previous job (clamp pressure, offset, tool table entry) is not re-verified before running a new job.", expression: "setup parameter carried over, not re-verified against the new job's requirement" }],
    latentStateEffects: [{ targetPath: "coolant/workholding state (future), failure.activeMode", effect: "Insufficient clamping force for the new operation's cutting loads." }],
    observations: { telemetry: ["Configured clamp pressure does not match the new job's documented requirement, if checked."], process: ["No independent re-verification step was performed at changeover."] },
    progression: [{ name: "changeover", description: "New job loaded, prior setting not re-verified", observableSymptoms: [] }, { name: "loss-of-grip", description: "Workpiece comes loose under cutting load", observableSymptoms: ["violent, sudden event; part and/or fixture ejected"] }],
    consequences: [{ description: "Workholding failure at speed - ejected part/fixture, real injury risk in the source incident.", severity: "machine-damage" }],
    appropriateResponses: [{ description: "Re-verify every carried-over setup parameter against the new job's documented requirement at every changeover, never assume the prior setting still applies.", competencyIds: ["setup-verification", "workholding-verification"] }],
    inappropriateResponses: [{ description: "Assume a setting from the prior job is still correct without checking it against the new job's spec.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Make changeover verification a discrete, checked step - never implicit.", competencyIds: ["workholding-verification"] }],
    competencies: ["setup-verification", "workholding-verification"],
  },
  {
    id: "grievance.no-baseline-before-tools-fail",
    title: "No baseline before tools fail",
    category: "tooling",
    severity: "quality",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/suddenly-breaking-end-mills-in-known-program.314247/", accessedDate: "2026-08-13", summarizedClaim: "Tooling that had been running fine starts failing, sometimes within minutes, with no wear photos or data captured from when the process was healthy - so root-cause analysis becomes guesswork." },
    ],
    triggerConditions: [{ description: "No tool-condition baseline exists from when the process was known-healthy, so a new failure has nothing to compare against.", expression: "no recorded healthy-state tool inspection for this tool/program combination" }],
    latentStateEffects: [{ targetPath: "tool.priorDamageNotes (absence of)", effect: "Root-cause analysis for a new failure has no reference point." }],
    observations: { process: ["No inspection record exists from a prior known-good run of this program/tool combination."] },
    progression: [{ name: "healthy-unrecorded", description: "Process runs well, no baseline captured", observableSymptoms: [] }, { name: "unexplained-failure", description: "Tool begins failing with no prior data to compare against", observableSymptoms: ["failure with no clear precursor in available records"] }],
    consequences: [{ description: "Troubleshooting becomes guesswork rather than comparison against a known-good baseline.", severity: "quality" }],
    appropriateResponses: [{ description: "Capture a tool-condition inspection at the start of a known-good run so later failures have something to compare against.", competencyIds: ["tooling-inspection", "troubleshooting"] }],
    inappropriateResponses: [{ description: "Only ever inspect tooling after a failure has already occurred.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Baseline-inspect tooling at the start of a validated run, not only after something goes wrong.", competencyIds: ["tooling-inspection"] }],
    competencies: ["tooling-inspection", "troubleshooting"],
  },
  {
    id: "grievance.thermal-shock-insert-failure",
    title: "Thermal-shock insert failure",
    category: "coolant",
    severity: "quality",
    validationStatus: "engineering-supported",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/inserts-failing-on-face-mill.364621/", accessedDate: "2026-08-13", summarizedClaim: "Applying coolant by 'dabbing' with a brush or squeeze bottle instead of full flood or fully dry cutting shatters insert tips via thermal shock." },
    ],
    triggerConditions: [{ description: "Coolant is applied intermittently to a hot cutting edge rather than continuously (flood) or not at all (dry).", expression: "coolant.flowAdequate is intermittently true/false during an active cut, not held constant" }],
    latentStateEffects: [{ targetPath: "tool.thermalDamageFraction", effect: "Repeated rapid heating/cooling cycles at the cutting edge, distinct from steady-state thermal wear." }],
    observations: { audio: ["Acoustic signature distinct from gradual wear - a sudden change tied to intermittent coolant contact, not a slow drift."], visual: ["Chipped/shattered insert tip rather than gradually worn flank."] },
    progression: [{ name: "intermittent-contact", description: "Coolant dabbed on rather than held constant", observableSymptoms: [] }, { name: "thermal-cycling", description: "Repeated rapid heat/cool cycles at the edge", observableSymptoms: [] }, { name: "shatter", description: "Insert tip fractures from accumulated thermal stress", observableSymptoms: ["sudden acoustic/load discontinuity"] }],
    consequences: [{ description: "Premature, sudden insert failure distinct from normal gradual wear-out.", severity: "quality" }],
    appropriateResponses: [{ description: "Choose full flood coolant or fully dry cutting for a given operation - avoid intermittent/partial coolant contact on a hot edge.", competencyIds: ["coolant-diagnosis", "tool-selection"] }],
    inappropriateResponses: [{ description: "Apply coolant intermittently (dabbing) to a cutting edge under continuous load.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Match coolant strategy (flood vs. dry) deliberately to the operation rather than defaulting to ad hoc partial application.", competencyIds: ["coolant-diagnosis"] }],
    competencies: ["coolant-diagnosis", "tool-selection"],
  },
  {
    id: "grievance.chip-management-on-new-machines",
    title: "Chip management on new machines",
    category: "chips",
    severity: "downtime",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/i-have-a-2023-dnm5700-is-the-coolant-chip-management-really-supposed-to-be-this-terrible.426392/", accessedDate: "2026-08-13", summarizedClaim: "Owners of a brand-new machine report the factory-standard chip conveyor chokes on fine swarf from small-diameter tooling, forcing shop-floor fixes like paint-strainer bags over the discharge or an aftermarket conveyor upgrade." },
    ],
    triggerConditions: [{ description: "Small-diameter tooling generates fine swarf faster than the chip-evacuation path can clear it.", expression: "chip.evacuationLoadFraction rising faster than the conveyor's rated clearing rate for fine swarf" }],
    latentStateEffects: [{ targetPath: "chip.evacuationLoadFraction, chip.formationQuality", effect: "Gradual buildup toward a clog, distinct from an instantaneous failure." }],
    observations: { visual: ["Visible swarf accumulation at the discharge chute over the course of a run."], telemetry: ["Rising evacuation-load indicator well before an actual stall."] },
    progression: [
      { name: "fine-swarf-generation", description: "Small-diameter tooling produces fine chips continuously", observableSymptoms: [] },
      { name: "gradual-accumulation", description: "Evacuation path load increases over the run", observableSymptoms: ["visible buildup at discharge"] },
      { name: "clog-and-stall", description: "Evacuation path fully blocks", observableSymptoms: ["unplanned stop"] },
    ],
    consequences: [{ description: "Unscheduled downtime from a preventable, gradually-visible clog.", severity: "downtime" }],
    appropriateResponses: [{ description: "Monitor chip evacuation load during long small-tool operations and clear proactively rather than running to a stall.", competencyIds: ["chip-management-awareness", "maintenance-awareness"] }],
    inappropriateResponses: [{ description: "Ignore visible swarf accumulation until the machine stalls on its own.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Schedule proactive chip-path clearing for known fine-swarf operations rather than waiting for a stall.", competencyIds: ["maintenance-awareness"] }],
    competencies: ["chip-management-awareness", "maintenance-awareness"],
  },
  {
    id: "grievance.post-processor-kinematics-mismatch",
    title: "Post-processor / kinematics mismatch",
    category: "programming-control",
    severity: "machine-damage",
    validationStatus: "engineering-supported",
    sourceReferences: [
      { url: "https://www.researchgate.net/publication/304490925_NX_CAM_post_processing_errors_Machine_data_file_generator_vs_post_builder", accessedDate: "2026-08-13", summarizedClaim: "A CAM post-processor's kinematic solver does not perfectly match the real machine's actual kinematics, so a toolpath that simulates clean in software can still gouge or collide when run on the real machine." },
    ],
    triggerConditions: [{ description: "A toolpath is trusted as safe solely because it simulated clean in CAM software, with no allowance for post/kinematic-model mismatch against the physical machine.", expression: "no dry-run/prove-out performed on the real machine before full-rate cutting" }],
    latentStateEffects: [{ targetPath: "failure.activeMode", effect: "A collision or gouge the software-level simulation gave no warning of." }],
    observations: { process: ["CAM simulation reported clear; the discrepancy only appears on the physical machine."] },
    progression: [{ name: "software-clear", description: "CAM simulation reports no collision", observableSymptoms: [] }, { name: "physical-mismatch", description: "Real machine kinematics differ from the post's model in some region", observableSymptoms: [] }, { name: "collision", description: "Gouge or crash occurs where software predicted none", observableSymptoms: ["unexpected impact/gouge despite a clean simulation report"] }],
    consequences: [{ description: "Machine or tool damage from a collision CAM software did not predict.", severity: "machine-damage" }],
    appropriateResponses: [{ description: "Treat a clean CAM simulation as necessary, not sufficient - always dry-run/prove-out new programs on the real machine before full-rate cutting.", competencyIds: ["safe-prove-out-reasoning", "troubleshooting"] }],
    inappropriateResponses: [{ description: "Run a new program at full rate on the strength of a clean CAM simulation alone.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Always dry-run/prove-out a new or changed program on the actual machine, regardless of CAM simulation results.", competencyIds: ["safe-prove-out-reasoning"] }],
    competencies: ["safe-prove-out-reasoning", "troubleshooting"],
  },
  {
    id: "grievance.gouge-check-must-be-rerun-manually",
    title: "Gouge check must be re-run manually",
    category: "programming-control",
    severity: "quality",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://industrialmonitordirect.com/blogs/knowledgebase/programming-4-axis-groove-toolpaths-in-siemens-nx-cam", accessedDate: "2026-08-13", summarizedClaim: "Collision/gouge detection in CAM software has to be manually re-run after every change to drive geometry or tool selection - gouges can slip through after what feels like a 'small' edit." },
    ],
    triggerConditions: [{ description: "A program is edited (geometry or tool change) and resumed without manually re-running collision/gouge verification.", expression: "program edited, verification not re-run before next cut" }],
    latentStateEffects: [{ targetPath: "failure.activeMode", effect: "An edit invalidates a prior verification without any automatic warning." }],
    observations: { process: ["A verification pass exists from before the edit, not after it."] },
    progression: [{ name: "verified", description: "Program passes gouge check", observableSymptoms: [] }, { name: "edited", description: "Geometry or tool selection changed", observableSymptoms: [] }, { name: "stale-verification", description: "Program run again trusting the now-invalid prior check", observableSymptoms: [] }],
    consequences: [{ description: "A gouge/collision that a re-run check would have caught.", severity: "quality" }],
    appropriateResponses: [{ description: "Re-run gouge/collision verification after every geometry or tool edit, treating any edit as invalidating the prior check.", competencyIds: ["safe-prove-out-reasoning"] }],
    inappropriateResponses: [{ description: "Treat a 'small' edit as not requiring re-verification.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Make re-verification after any edit a non-negotiable habit, not a judgment call about how 'small' the edit was.", competencyIds: ["safe-prove-out-reasoning"] }],
    competencies: ["safe-prove-out-reasoning"],
  },
  {
    id: "grievance.rush-customers-who-pay-slowly",
    title: "Rush customers who pay slowly",
    category: "production-business-friction",
    severity: "nuisance",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/do-you-charge-an-expedite-fee-for-hot-jobs.267984/", accessedDate: "2026-08-13", summarizedClaim: "Customers who demand expedited turnaround are often the same slow-pay accounts; shops eat schedule disruption without matching cash-flow benefit unless they explicitly charge an expedite premium (commonly 20-25%)." },
    ],
    triggerConditions: [{ description: "An expedite request arrives from a customer with a poor payment history, and no expedite premium is charged.", expression: "expedite requested, no fee applied, customer payment terms already slow" }],
    latentStateEffects: [{ targetPath: "cash-flow model (not yet built)", effect: "Schedule disruption absorbed without compensating cash-flow benefit." }],
    observations: { process: ["Customer payment history shows a pattern of slow payment relative to invoice terms."] },
    progression: [{ name: "request", description: "Expedite requested", observableSymptoms: [] }, { name: "unpriced-disruption", description: "Schedule reshuffled without an expedite fee", observableSymptoms: ["other jobs displaced"] }],
    consequences: [{ description: "Schedule and cash-flow strain with no offsetting benefit.", severity: "nuisance" }],
    appropriateResponses: [{ description: "Price expedite requests explicitly, especially for accounts with a slow-pay history.", competencyIds: [] }],
    inappropriateResponses: [{ description: "Absorb expedite disruption for free regardless of customer payment history.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Have a standing expedite-fee policy tied to customer payment history.", competencyIds: [] }],
    competencies: [],
  },
  {
    id: "grievance.undocumented-scope-creep",
    title: "Undocumented scope creep",
    category: "quality-documentation",
    severity: "nuisance",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://quality.eleapsoftware.com/glossary/engineering-change-order-in-qms-complete-guide/", accessedDate: "2026-08-13", summarizedClaim: "Mid-project customer changes absorbed as unpaid work, without a formal change-order record, silently erode margin even when the change itself is 'free.'" },
    ],
    triggerConditions: [{ description: "A customer requests a mid-project change and it is actioned without a documented change order.", expression: "change actioned, no ECO/ECN record created" }],
    latentStateEffects: [{ targetPath: "quality/traceability records (future)", effect: "The design-history record no longer matches what was actually built, and the cost of the change is invisible." }],
    observations: { process: ["No change-order paperwork exists for a change that was actually made."] },
    progression: [{ name: "request", description: "Customer requests a change", observableSymptoms: [] }, { name: "unrecorded-action", description: "Change is made without an ECO", observableSymptoms: ["design-history record diverges from as-built part"] }],
    consequences: [{ description: "Margin erosion and a broken traceability record, discovered later if ever.", severity: "nuisance" }],
    appropriateResponses: [{ description: "Document every change, even a zero-cost one, through a formal change-order process.", competencyIds: ["quality-disposition"] }],
    inappropriateResponses: [{ description: "Action a customer change verbally with no paper trail.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Require an ECO/ECN record before any mid-project change is actioned, regardless of whether it's billed.", competencyIds: ["quality-disposition"] }],
    competencies: ["quality-disposition"],
  },
  {
    id: "grievance.material-substituted-cert-mismatch",
    title: "Material substituted, cert doesn't match",
    category: "material",
    severity: "quality",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/material-certs-how-do-you-know-if-its-for-what-you-received.314414/", accessedDate: "2026-08-13", summarizedClaim: "A shop ordered 6082-T651 and received 5083-O; hardness testing caught the substitution, but the delivery paperwork still claimed the ordered alloy, and no mill certificate was ever actually provided despite requests." },
    ],
    triggerConditions: [{ description: "Incoming material's paperwork claims one alloy/temper but the physical material is different, and no hardness/material verification is performed at receiving.", expression: "no incoming material verification against the certificate" }],
    latentStateEffects: [{ targetPath: "material profile (future)", effect: "Parts get machined from the wrong material despite paperwork saying otherwise." }],
    observations: { process: ["Hardness test result disagrees with the certificate's stated alloy/temper.", "No mill certificate was ever actually supplied, only a delivery note."] },
    progression: [{ name: "delivery", description: "Material arrives with a paper cert claiming the ordered spec", observableSymptoms: [] }, { name: "unverified-acceptance", description: "Material accepted into stock without independent verification", observableSymptoms: [] }, { name: "late-discovery", description: "Mismatch found only if/when someone tests it", observableSymptoms: ["hardness or other property disagrees with the cert"] }],
    consequences: [{ description: "Parts made from the wrong material; potential nonconformance discovered late or never.", severity: "quality" }],
    appropriateResponses: [{ description: "Verify incoming material against its certificate (hardness test, spark test, or equivalent) rather than trusting paperwork alone.", competencyIds: ["metrology-selection", "quality-disposition"] }],
    inappropriateResponses: [{ description: "Accept material into production stock on the strength of a delivery note alone, without a genuine mill certificate.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Require and verify an actual mill certificate for incoming material, not just a delivery note.", competencyIds: ["quality-disposition"] }],
    competencies: ["metrology-selection", "quality-disposition"],
  },
  {
    id: "grievance.certs-never-travel-with-metal",
    title: "Certs never travel with the metal",
    category: "material",
    severity: "nuisance",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/correlating-material-certs-to-machining-problems.446383/", accessedDate: "2026-08-13", summarizedClaim: "Bar stock frequently arrives with only a sticker, no attached mill certificate, forcing shops to chase suppliers for paperwork after the fact and undermining heat-number traceability." },
    ],
    triggerConditions: [{ description: "Material arrives with only a tag/sticker and no accompanying mill certificate.", expression: "material received, certificate not attached" }],
    latentStateEffects: [{ targetPath: "material profile (future)", effect: "Heat-number traceability is broken from the moment the material enters the shop." }],
    observations: { process: ["No certificate on file for a given heat number at the time it's needed (e.g. for an audit or a customer request)."] },
    progression: [{ name: "receipt", description: "Material arrives without its certificate", observableSymptoms: [] }, { name: "traceability-gap", description: "Certificate is chased after the fact, sometimes never obtained", observableSymptoms: [] }],
    consequences: [{ description: "Broken traceability discovered at the worst possible time - an audit or a customer request.", severity: "nuisance" }],
    appropriateResponses: [{ description: "Refuse to stock material for traceable work without its certificate in hand at receiving.", competencyIds: ["quality-disposition"] }],
    inappropriateResponses: [{ description: "Accept and use material for traceable work while the certificate is still outstanding.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Make certificate-in-hand a condition of accepting material into traceable stock.", competencyIds: ["quality-disposition"] }],
    competencies: ["quality-disposition"],
  },
  {
    id: "grievance.procedure-gaps-surface-as-audit-hits",
    title: "Procedure gaps surface as audit hits",
    category: "quality-documentation",
    severity: "quality",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://elsmar.com/elsmarqualityforum/threads/cb-and-internal-auditors-most-common-nonconformities-against-as9100d.71979/", accessedDate: "2026-08-13", summarizedClaim: "A shop was cited for lacking a documented counterfeit-parts procedure, then cited again by a different auditor for an incomplete version of that same procedure; another organization was separately dinged when a calibration lab quietly fell off its approved supplier list through plain administrative oversight." },
    ],
    triggerConditions: [{ description: "A required QMS procedure is missing or incomplete at the time of an external audit.", expression: "procedure gap exists, undetected until audit" }],
    latentStateEffects: [{ targetPath: "quality/certification records (future)", effect: "A documentation gap becomes a formal nonconformance." }],
    observations: { process: ["No internal review caught the procedure gap before an external auditor did."] },
    progression: [{ name: "gap-exists", description: "Procedure missing/incomplete, unnoticed internally", observableSymptoms: [] }, { name: "audit-finding", description: "External auditor identifies the gap", observableSymptoms: ["formal nonconformance issued"] }],
    consequences: [{ description: "Formal audit finding, potential repeat finding if the fix is itself incomplete.", severity: "quality" }],
    appropriateResponses: [{ description: "Periodically self-audit required procedures for completeness rather than waiting for an external auditor to find the gap.", competencyIds: ["quality-disposition"] }],
    inappropriateResponses: [{ description: "Treat QMS procedure maintenance as a one-time task rather than an ongoing check.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Schedule periodic internal review of required procedures against current requirements.", competencyIds: ["quality-disposition"] }],
    competencies: ["quality-disposition"],
  },
  {
    id: "grievance.cited-for-root-cause-paperwork",
    title: "Cited for root-cause paperwork",
    category: "quality-documentation",
    severity: "quality",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://elsmar.com/elsmarqualityforum/threads/minor-finding-during-as9100-audit-documentation-in-oasis-incorrect.90731/", accessedDate: "2026-08-13", summarizedClaim: "A shop received a minor nonconformance under AS9100 clause 10.2.1 for 'ineffective processes in determining causes of nonconformities' - cited for the quality of the root-cause analysis itself, not for the underlying defect." },
    ],
    triggerConditions: [{ description: "A corrective action's root-cause analysis is shallow or unsubstantiated, even when the immediate defect was correctly fixed.", expression: "root-cause documentation insufficient, defect itself resolved" }],
    latentStateEffects: [{ targetPath: "quality/certification records (future)", effect: "A correctly-fixed defect still produces a nonconformance because of how the cause was documented." }],
    observations: { process: ["Corrective-action record shows a fix without a substantiated root-cause chain."] },
    progression: [{ name: "defect-fixed", description: "Immediate nonconformance corrected", observableSymptoms: [] }, { name: "shallow-root-cause", description: "Root-cause analysis not substantiated", observableSymptoms: ["audit finding on the analysis itself"] }],
    consequences: [{ description: "A nonconformance issued for documentation quality, independent of whether the part-level fix was correct.", severity: "quality" }],
    appropriateResponses: [{ description: "Substantiate root-cause analysis with actual evidence, not just a stated fix, even when the immediate defect is resolved.", competencyIds: ["troubleshooting", "quality-disposition"] }],
    inappropriateResponses: [{ description: "Document a corrective action as 'fixed' without a substantiated causal chain.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Treat root-cause documentation as evidence-based, not a formality to complete quickly.", competencyIds: ["troubleshooting"] }],
    competencies: ["troubleshooting", "quality-disposition"],
  },
  {
    id: "grievance.talent-pipeline-squeeze",
    title: "Talent pipeline squeeze",
    category: "production-business-friction",
    severity: "nuisance",
    validationStatus: "anecdotal",
    sourceReferences: [
      { url: "https://www.nist.gov/node/1529026", accessedDate: "2026-08-13", summarizedClaim: "Machinist turnover and a broader skilled-trades shortage force manufacturing leadership toward reactive hiring or missed delivery commitments. Explicitly flagged in the source doc as directionally real but under-sourced - no specific vivid anecdote was found in this research pass." },
    ],
    triggerConditions: [{ description: "Staffing model (not yet built).", expression: "not modeled yet" }],
    latentStateEffects: [],
    observations: {},
    progression: [],
    consequences: [{ description: "Reactive hiring or missed delivery commitments under sustained skilled-trades shortage.", severity: "nuisance" }],
    appropriateResponses: [],
    inappropriateResponses: [],
    preventiveBehaviors: [],
    competencies: [],
  },
  {
    id: "grievance.owner-burnout",
    title: "Owner burnout",
    category: "production-business-friction",
    severity: "nuisance",
    validationStatus: "anecdotal",
    sourceReferences: [
      { url: "https://21hats.substack.com/p/business-owners-say-theyre-burning", accessedDate: "2026-08-13", summarizedClaim: "Roughly 62% of small-business owners report burnout at least monthly and 81% report exhaustion in the last year. Explicitly cross-industry data, not machining-specific." },
    ],
    triggerConditions: [{ description: "Sustained-workload/focus model (not yet built).", expression: "not modeled yet" }],
    latentStateEffects: [],
    observations: {},
    progression: [],
    consequences: [{ description: "Degraded decision quality and increased error rate under sustained overwork - directionally plausible, not machining-specific evidence.", severity: "nuisance" }],
    appropriateResponses: [],
    inappropriateResponses: [],
    preventiveBehaviors: [],
    competencies: [],
  },
  {
    id: "grievance.auction-machine-hidden-extraction-cost",
    title: "Auction machine, hidden extraction cost",
    category: "production-business-friction",
    severity: "nuisance",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/machine-auction-results.389720/", accessedDate: "2026-08-13", summarizedClaim: "A buyer got a machine cheap at auction, then discovered the seller's building doorway was too small for the machine to leave, requiring structural demolition just to extract it - the purchase price ended up being the smallest part of the real cost." },
    ],
    triggerConditions: [{ description: "A used-machine purchase decision is made without verifying physical extraction/rigging logistics beforehand.", expression: "purchase committed, extraction logistics unverified" }],
    latentStateEffects: [{ targetPath: "marketplace model (not yet built)", effect: "A cheap sale price hides a much larger real total cost." }],
    observations: { process: ["No rigging/clearance assessment was performed before committing to purchase."] },
    progression: [{ name: "cheap-bid-wins", description: "Low purchase price looks like a good deal", observableSymptoms: [] }, { name: "extraction-discovery", description: "Physical removal turns out to be blocked", observableSymptoms: ["doorway/clearance insufficient"] }],
    consequences: [{ description: "Structural demolition cost far exceeding the machine's purchase price.", severity: "nuisance" }],
    appropriateResponses: [{ description: "Verify extraction/rigging logistics before committing to a used-machine purchase, not after winning the bid.", competencyIds: [] }],
    inappropriateResponses: [{ description: "Bid based on price alone with no logistics check.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Always assess extraction path/rigging feasibility before bidding.", competencyIds: [] }],
    competencies: [],
  },
  {
    id: "grievance.auction-sniping",
    title: "Auction sniping",
    category: "production-business-friction",
    severity: "nuisance",
    validationStatus: "anecdotal",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/used-cnc-machinery-values.361444/", accessedDate: "2026-08-13", summarizedClaim: "A machine sat at a $1.00 bid for a week, then got sniped in the final 30 minutes - a low current bid says nothing reliable about real demand or final price." },
    ],
    triggerConditions: [{ description: "A bidder assumes a low current auction price reflects low final demand.", expression: "current-bid-low interpreted as final-price-low" }],
    latentStateEffects: [{ targetPath: "marketplace model (not yet built)", effect: "Misjudging likely final price based on a misleading mid-auction signal." }],
    observations: { process: ["Current bid stays flat for an extended period, then jumps sharply near close."] },
    progression: [{ name: "flat-bidding", description: "Price stays artificially low for most of the auction window", observableSymptoms: [] }, { name: "last-minute-jump", description: "Real demand surfaces only in the closing minutes", observableSymptoms: ["sharp price increase near close"] }],
    consequences: [{ description: "A buyer who assumed a low mid-auction price would hold gets outbid or overpays relative to their expectation.", severity: "nuisance" }],
    appropriateResponses: [{ description: "Judge auction value from comparable sales/market data, not from the current mid-auction bid.", competencyIds: [] }],
    inappropriateResponses: [{ description: "Assume a flat, low current bid predicts the final price.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Research comparable market values before an auction rather than reacting to the live bid alone.", competencyIds: [] }],
    competencies: [],
  },
  {
    id: "grievance.serial-scammer-listings",
    title: "Serial-scammer listings",
    category: "production-business-friction",
    severity: "nuisance",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/the-scammers-are-thick-beware.413345/page-2", accessedDate: "2026-08-13", summarizedClaim: "Documented pattern of fraudulent used-machinery listings reusing stolen photos, rotating fake seller names, promising suspiciously convenient 'palletized and ready to ship' machines, and cycling payment details - including one case that used a real, deceased dealer's identity." },
    ],
    triggerConditions: [{ description: "A used-equipment listing shows red flags (below-market price, reused/generic photos, pressure for upfront wire payment, no verifiable seller history) and these are not checked before committing funds.", expression: "listing red flags present, not verified before payment" }],
    latentStateEffects: [{ targetPath: "marketplace model (not yet built)", effect: "Funds sent for equipment that does not exist or will never be delivered." }],
    observations: { process: ["No independent verification of seller identity, serial number with the OEM, or in-person inspection was performed before payment."] },
    progression: [{ name: "attractive-listing", description: "Below-market price, convenient claims", observableSymptoms: [] }, { name: "payment-pressure", description: "Seller pushes for immediate wire transfer", observableSymptoms: [] }, { name: "loss", description: "Funds sent, no equipment received", observableSymptoms: [] }],
    consequences: [{ description: "Total loss of funds sent for nonexistent equipment.", severity: "nuisance" }],
    appropriateResponses: [{ description: "Verify seller identity and equipment serial number independently (with the OEM where possible) before sending any payment; never wire funds on pressure alone.", competencyIds: [] }],
    inappropriateResponses: [{ description: "Wire payment upfront based on listing photos and seller claims alone.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Require in-person inspection or escrow for any significant used-equipment purchase from an unverified seller.", competencyIds: [] }],
    competencies: [],
  },
  {
    id: "grievance.power-loss-mid-cut",
    title: "Power loss mid-cut",
    category: "maintenance",
    severity: "machine-damage",
    validationStatus: "corroborated",
    sourceReferences: [
      { url: "https://www.practicalmachinist.com/forum/threads/power-outages-and-damaged-machine-servo-drives.253507/", accessedDate: "2026-08-13", summarizedClaim: "Power dropped with multiple lines during active cutting, destroying roughly $30k of PCD tooling and causing ~$20k in repair costs for machines that would not restart. Servo/VFD drives were the common failure point; line reactors/isolation transformers are a mitigating retrofit most shops have not budgeted for." },
    ],
    triggerConditions: [{ description: "Facility power is interrupted while a cut is actively in progress, with no line conditioning/isolation in place.", expression: "power interruption during active cutting, no line reactor/isolation transformer installed" }],
    latentStateEffects: [{ targetPath: "failure.activeMode = 'power-loss', tool state, machine servo/drive state (future)", effect: "Uncommanded stop mid-cut; possible drive damage preventing restart." }],
    observations: { visual: ["All machine indicators go dark simultaneously."], telemetry: ["Uncommanded stop with no preceding alarm."] },
    progression: [{ name: "active-cutting", description: "Normal cut in progress", observableSymptoms: [] }, { name: "interruption", description: "Power drops mid-cycle", observableSymptoms: ["immediate uncommanded stop"] }, { name: "damage-assessment", description: "Tool/part/drive condition unknown until power returns and machine is inspected", observableSymptoms: [] }],
    consequences: [{ description: "Destroyed tooling and potential machine-drive damage; large repair cost and downtime.", severity: "machine-damage" }],
    appropriateResponses: [{ description: "Inspect tool, part, and machine condition carefully after any power-loss event before attempting to resume, and consider line-conditioning equipment for known unstable facility power.", competencyIds: ["troubleshooting", "maintenance-awareness"] }],
    inappropriateResponses: [{ description: "Immediately resume the cycle after power returns without inspecting for damage.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Install line reactors/isolation transformers where facility power is known to be unstable.", competencyIds: ["maintenance-awareness"] }],
    competencies: ["troubleshooting", "maintenance-awareness"],
  },
  {
    id: "grievance.legacy-controllers-ransomware-exposure",
    title: "Legacy controllers as ransomware exposure",
    category: "maintenance",
    severity: "safety-critical",
    validationStatus: "validated",
    sourceReferences: [
      { url: "https://www.securityweek.com/cnc-machines-vulnerable-hijacking-data-theft-damaging-cyberattacks/", accessedDate: "2026-08-13", summarizedClaim: "A named defense-sector precision-machining subcontractor was hit by ransomware with leaked files tied to major aerospace/defense primes; a separate shop spent over $200k and five weeks down recovering from a ransomware incident. Root cause repeatedly cited: CNC controllers running unpatchable legacy operating systems, with removable USB media as the common infection vector." },
    ],
    triggerConditions: [{ description: "A CNC controller runs an unpatchable legacy OS with no network segmentation, and removable media (USB) is used on it without controls.", expression: "legacy unpatched controller OS, flat network, uncontrolled USB use" }],
    latentStateEffects: [{ targetPath: "machine controller state (future)", effect: "Machine programs and potentially the controller itself become encrypted/inoperable." }],
    observations: { visual: ["Controller displays a lock/ransom message instead of its normal interface."], process: ["No network segmentation existed between the affected machine and the rest of the shop's systems.", "Backups, if they exist, have not been recently verified."] },
    progression: [{ name: "exposure", description: "Legacy controller, flat network, uncontrolled USB use", observableSymptoms: [] }, { name: "infection", description: "Malware introduced via removable media", observableSymptoms: [] }, { name: "lockout", description: "Controller/programs encrypted, machine inoperable", observableSymptoms: ["ransom message on controller display"] }],
    consequences: [{ description: "Multi-week downtime and significant direct recovery cost; potential data exposure for a defense-sector shop specifically.", severity: "safety-critical" }],
    appropriateResponses: [{ description: "Segment legacy controllers from the general network, control/restrict removable media use, and maintain verified, tested backups.", competencyIds: ["maintenance-awareness"] }],
    inappropriateResponses: [{ description: "Allow uncontrolled USB use on an unpatchable, unsegmented legacy controller.", competencyIds: [] }],
    preventiveBehaviors: [{ description: "Network-segment legacy controllers and control removable-media use as a standing policy, not a reaction to an incident.", competencyIds: ["maintenance-awareness"] }],
    competencies: ["maintenance-awareness"],
  },
];
