const capabilities = [
  { number: "01", title: "Precision machining", copy: "Complex parts, exacting tolerances, and disciplined execution from first article through repeat production.", detail: "Aerospace / Energy / Industrial" },
  { number: "02", title: "Engineered plastics", copy: "Material expertise and responsive supply for demanding applications where consistency matters.", detail: "Materials / Distribution / Fabrication" },
  { number: "03", title: "Quality systems", copy: "Inspection, traceability, and process control are built into the work - not added after it.", detail: "First-piece / In-process / Final" },
];
const systems = [
  ["Live production visibility", "Machine state, work-center capacity, and priority signals brought into one operational view."],
  ["First-piece confidence", "Shared quality checkpoints help teams see, act, and communicate before the next part runs."],
  ["Tool intelligence", "Shop-floor knowledge, tooling cost, and process guidance organized for faster decisions."],
  ["Connected handoffs", "Structured shift notes keep operators, supervisors, and the next shift working from the same facts."],
];
export default function Home() {
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="Advanced home"><span className="brand-mark" aria-hidden="true">A</span><span>ADVANCED</span></a><nav className="desktop-nav" aria-label="Primary navigation"><a href="#capabilities">Capabilities</a><a href="#quality">Quality</a><a href="#systems">Inside Advanced</a><a href="#story">Company</a></nav><a className="header-cta" href="#contact">Start a conversation <span aria-hidden="true">+</span></a></header>
    <section className="hero" id="top"><video className="hero-video" autoPlay muted loop playsInline aria-hidden="true"><source src="https://advcosinc.com/wp-content/uploads/2024/07/Advance-Intro-Reel-Long_2.mp4" type="video/mp4" /></video><div className="hero-shade" /><div className="hero-grid" aria-hidden="true" /><p className="eyebrow hero-eyebrow"><span /> Precision manufacturing / USA</p><div className="hero-copy"><h1>We make<br />what matters.</h1><div className="hero-side"><p>Precision machining, engineered materials, and a team built to solve the hard manufacturing problems.</p><a className="circle-link" href="#capabilities" aria-label="Explore Advanced capabilities">v</a></div></div><div className="hero-foot"><span>Built on craft</span><span>Driven by data</span><span>Ready for what's next</span></div></section>
    <section className="statement section-pad"><p className="eyebrow"><span /> What we believe</p><h2>Good enough<br />doesn't leave<br />our floor.</h2><p className="statement-copy">Advanced brings experienced people, modern equipment, and connected operations together to make ambitious work feel dependable.</p></section>
    <section className="capabilities" id="capabilities">{capabilities.map((item) => <article className="capability" key={item.number}><div className="cap-number">({item.number})</div><h3>{item.title}</h3><p>{item.copy}</p><div className="cap-bottom"><span>{item.detail}</span><span aria-hidden="true">+</span></div></article>)}</section>
    <section className="quality" id="quality"><div className="quality-orbit" aria-hidden="true"><span>Q</span></div><div className="quality-copy"><p className="eyebrow light"><span /> Quality is the system</p><h2>Precision<br />you can trace.</h2><p>From first-piece review to final inspection, quality is visible at every stage. Our processes help teams catch issues earlier, share decisions faster, and deliver with confidence.</p><a className="text-link" href="#contact">Talk to our team <span>+</span></a></div><div className="quality-stats" aria-label="Quality principles"><div><strong>01</strong><span>Plan the work</span></div><div><strong>02</strong><span>Control the process</span></div><div><strong>03</strong><span>Verify the result</span></div></div></section>
    <section className="systems section-pad" id="systems"><div className="systems-heading"><p className="eyebrow"><span /> Inside Advanced</p><h2>A smarter<br />shop floor.</h2><p>We build practical systems around the people doing the work - turning production signals into clear next actions.</p></div><div className="systems-list">{systems.map(([title, copy], index) => <article key={title}><span className="system-index">0{index + 1}</span><h3>{title}</h3><p>{copy}</p><span className="system-arrow" aria-hidden="true">+</span></article>)}</div></section>
    <section className="story" id="story"><div className="story-word" aria-hidden="true">ADV</div><div className="story-copy"><p className="eyebrow light"><span /> Our story</p><h2>Built to adapt.<br />Grounded in craft.</h2><p>Advanced has evolved through plastics distribution and precision manufacturing by staying close to customers, investing in capability, and never losing sight of the work itself.</p></div></section>
    <section className="contact" id="contact"><p className="eyebrow"><span /> Your next project</p><h2>Let's make<br />it real.</h2><div className="contact-row"><p>Bring us the print, the problem, or the possibility. We'll bring the right people to the table.</p><a href="https://advcosinc.com/contact/">Start a conversation <span aria-hidden="true">+</span></a></div></section>
    <footer><a className="brand footer-brand" href="#top"><span className="brand-mark">A</span><span>ADVANCED</span></a><div><span>Precision machining</span><span>Engineered plastics</span><span>Connected operations</span></div><div><a href="https://www.linkedin.com/company/advanced-plastics-and-machining/">LinkedIn +</a><a href="https://advcosinc.com/careers/">Careers +</a></div><p>Copyright 2026 Advanced. Built for the work ahead.</p></footer>
  </main>;
}
