"use client";
import { useEffect, useRef } from "react";
import * as THREE from "three";
import type { ToolPoint } from "./gcode-engine";
import styles from "./part-preview.module.css";
type Props = { points: ToolPoint[]; frame: number; accent: string; material: string; tool: number; passes: number; finalDepth: number };
const clamp = (value:number,min:number,max:number) => Math.max(min, Math.min(max, value));

export default function PartPreview(props: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null), propsRef = useRef(props);
  useEffect(() => { propsRef.current = props; }, [props]);
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return; let renderer: THREE.WebGLRenderer;
    try { renderer = new THREE.WebGLRenderer({ canvas, antialias:true, alpha:false, powerPreference:"high-performance" }); } catch { return; }
    renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.25;
    const scene=new THREE.Scene(); scene.background=new THREE.Color(0x03090b); scene.fog=new THREE.FogExp2(0x061418,.035);
    const camera=new THREE.PerspectiveCamera(37,1,.1,100); scene.add(new THREE.HemisphereLight(0xdaf8ff,0x091114,2.1));
    const key=new THREE.DirectionalLight(0xffffff,4.7); key.position.set(10,18,8); scene.add(key); const rim=new THREE.PointLight(0x19d8ff,15,34,2); rim.position.set(-10,7,-9); scene.add(rim);
    const floor=new THREE.GridHelper(44,26,0x1d6675,0x102a31); floor.position.y=-2.8; (floor.material as THREE.Material).transparent=true; (floor.material as THREE.Material).opacity=.44; scene.add(floor);
    const base=new THREE.Mesh(new THREE.BoxGeometry(13,.45,10),new THREE.MeshStandardMaterial({color:0x344f58,metalness:.82,roughness:.3})); base.position.y=-2.55; scene.add(base); const edge=new THREE.LineSegments(new THREE.EdgesGeometry(base.geometry),new THREE.LineBasicMaterial({color:0xdafaff,transparent:true,opacity:.6})); edge.position.copy(base.position); scene.add(edge); const cols=28, rows=22, cellWidth=13/cols, cellDepth=10/rows, maxHeight=2.35, cutDepth=new Float32Array(cols*rows), matrix=new THREE.Matrix4(); const stockBlocks=new THREE.InstancedMesh(new THREE.BoxGeometry(cellWidth*.94,1,cellDepth*.94),new THREE.MeshStandardMaterial({color:0xa9c4ca,metalness:.88,roughness:.24}),cols*rows); stockBlocks.instanceMatrix.setUsage(THREE.DynamicDrawUsage); scene.add(stockBlocks);
    const traces=new THREE.Group(); scene.add(traces); const cutter=new THREE.Group(); const holder=new THREE.Mesh(new THREE.CylinderGeometry(.62,.72,2.8,18),new THREE.MeshStandardMaterial({color:0x1b3138,metalness:.9,roughness:.22})); holder.position.y=2.2; cutter.add(holder); const bit=new THREE.Mesh(new THREE.CylinderGeometry(.25,.35,2.6,12),new THREE.MeshStandardMaterial({color:0x7de6ff,metalness:.95,roughness:.16,emissive:0x07323e})); bit.position.y=-.42; cutter.add(bit); scene.add(cutter); const contact=new THREE.PointLight(0x6aeaff,0,10,2); scene.add(contact);
    const drag={active:false,x:0,y:0,yaw:-.55,pitch:.45}; const down=(event:PointerEvent)=>{drag.active=true;drag.x=event.clientX;drag.y=event.clientY;canvas.setPointerCapture(event.pointerId);}; const move=(event:PointerEvent)=>{if(!drag.active)return;drag.yaw+=(event.clientX-drag.x)*.008;drag.pitch=clamp(drag.pitch+(event.clientY-drag.y)*.006,.12,1.08);drag.x=event.clientX;drag.y=event.clientY;}; const up=()=>{drag.active=false;}; canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);
    const resize=()=>{const rect=canvas.getBoundingClientRect();renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(Math.max(1,rect.width),Math.max(1,rect.height),false);camera.aspect=Math.max(1,rect.width)/Math.max(1,rect.height);camera.updateProjectionMatrix();}; const observer=new ResizeObserver(resize);observer.observe(canvas);resize();let animation=0;
    const draw=(time:number)=>{const live=propsRef.current,visible=live.points.slice(0,Math.max(1,live.frame)),done=visible.filter(point=>point.cut&&point.z<0),all=live.points.filter(point=>point.cut&&point.z<0);cutDepth.fill(0);done.forEach(point=>{const column=clamp(Math.round(point.x/40*(cols-1)),0,cols-1),row=clamp(Math.round(point.y/40*(rows-1)),0,rows-1),radius=Math.abs(point.z)>2.35?1:0;for(let y=Math.max(0,row-radius);y<=Math.min(rows-1,row+radius);y+=1)for(let x=Math.max(0,column-radius);x<=Math.min(cols-1,column+radius);x+=1)cutDepth[y*cols+x]=Math.max(cutDepth[y*cols+x],Math.abs(point.z));});for(let row=0;row<rows;row+=1)for(let column=0;column<cols;column+=1){const depth=cutDepth[row*cols+column],height=Math.max(.22,maxHeight-depth*.68);matrix.compose(new THREE.Vector3(-6.5+(column+.5)*cellWidth,-2.325+height/2,-5+(row+.5)*cellDepth),new THREE.Quaternion(),new THREE.Vector3(1,height,1));stockBlocks.setMatrixAt(row*cols+column,matrix);}stockBlocks.instanceMatrix.needsUpdate=true;traces.clear();const line=(points:ToolPoint[],color:string,opacity:number)=>{if(points.length<2)return;const geo=new THREE.BufferGeometry().setFromPoints(points.map(point=>new THREE.Vector3((point.x-20)*.31,.12+point.z*.24,(point.y-20)*.31)));traces.add(new THREE.Line(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity})));};line(all,"#17414d",.8);line(done,live.accent,1);const head=visible.at(-1)??live.points[0]??{x:0,y:0,z:4,cut:false,line:0,feed:0};cutter.position.set((head.x-20)*.31,.9+Math.max(head.z,-2.6)*.3,(head.y-20)*.31);cutter.rotation.y=time*.02;contact.position.copy(cutter.position);contact.position.y-=1.8;contact.color.set(live.accent);contact.intensity=head.cut?6:1.5;const radius=22;camera.position.set(Math.sin(drag.yaw)*Math.cos(drag.pitch)*radius,Math.sin(drag.pitch)*radius+1.5,Math.cos(drag.yaw)*Math.cos(drag.pitch)*radius);camera.lookAt(0,-1,0);renderer.render(scene,camera);animation=requestAnimationFrame(draw);};animation=requestAnimationFrame(draw);
    return()=>{cancelAnimationFrame(animation);observer.disconnect();canvas.removeEventListener("pointerdown",down);canvas.removeEventListener("pointermove",move);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("pointercancel",up);scene.traverse(object=>{if(object instanceof THREE.Mesh||object instanceof THREE.Line){object.geometry.dispose();const mats=Array.isArray(object.material)?object.material:[object.material];mats.forEach(mat=>mat.dispose());}});renderer.dispose();};
  },[]);
  const visible=props.points.slice(0,Math.max(1,props.frame)),head=visible.at(-1)??props.points[0],complete=Math.round(visible.filter(point=>point.cut).length/Math.max(1,props.points.filter(point=>point.cut).length)*100);
  return <div className={styles.preview} aria-label="Live WebGL part preview generated from the current G-code path"><canvas ref={canvasRef} aria-label="Interactive 3D aluminum stock and cutter simulation. Drag to orbit; use normal page scrolling."/><div className={styles.readout}><b>LIVE WEBGL PART / SIM</b><span>{props.material} · T{props.tool} · {props.passes} PASS</span><span>Z {head?.z.toFixed(2)??"0.00"} MM · {complete}% EXECUTED</span></div><div className={styles.caption}><span><i style={{background:props.accent}}/> LIVE CUT PATH</span><span>DRAG TO ORBIT · SCROLL PAGE</span></div></div>;
}
